version: '3'

services:
  fantasy-db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - fantasy-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: somepassword
      POSTGRES_USER: example

volumes:
  fantasy-db-data:
    driver: local
